# config.yaml
defaults:
  - _self_
  - override hydra/job_logging: disabled  # optional
  - override hydra/hydra_logging: disabled  # optional

## Main options
outdir: "./outputs_SimVip_July"   

# Main Model Config 
overall_model: SimVip_base
model_variant: SimVip_base

# Hydra config 
hydra:
  run:
    dir: outputs/${overall_model}/${model_variant}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: true  # optional: changes working directory to hydra.run.dir      


data:
  dataset_path: "/home/tm3076/scratch/pytorch_learning_tiles"
  patch_coords_file: "zarred_UVSST_x_y_coordinates_noland_nonan.npy"
  infields: ["zarr_llc4320_SSH_tiles_4km_filtered", "zarr_llc4320_SST_tiles_4km"]
  outfields: ["zarr_llc4320_SSH_tiles_4km_filtered"]
  in_mask_list: ["nadir", "cloud_rho"]
  out_mask_list: ["swot_central"]
  in_transform_list: ["std_global_mean_ssh_norm", "std_global_mean_sst_norm"]
  out_transform_list: ["std_global_mean_ssh_norm"]
  mean_ssh: 0
  std_ssh: 0.0453692672359483
  mean_sst: 15.956900367755182
  std_sst: 5.987649544923141
  N_t: 10
  timesteps_range: [20, 360, 2] # [start, stop, step]
  batch_size: 64
  return_masks: False
  cloud_rho: 0.5

model:
  Number_timesteps: 10
  alpha0: 1
  alpha1: 10
  alpha2: 10
  lr: 1e-6
  drop: 0.2
  drop_path: 0.15
  model_type: "gSTA"
  multiprocessing: True
  masked_loss: True

training:
  num_epochs: 100
  checkpoint_dir: "checkpoints"
  workers: 8
  enable_profiler: True

wandb:
  model_name: ${hydra.job.name}_${now:%Y-%m-%d}-${now:%H-%M-%S}
  project: "SimVip_video_inpainting"
