model_variant: C0_0X4_10rho_lr1e-7_test

wandb:
  project: "SimVip_video_inpainting"
  model_name: ${model_variant}_${now:%Y-%m-%d}_${now:%H-%M-%S}

defaults:
  - 000_base_config_Greene

data:
  patch_coords_file: "zarred_UVSST_x_y_coordinates_noland_nonan.npy"
  infields: ["zarr_llc4320_SSH_tiles_4km_filtered", "zarr_llc4320_SST_tiles_4km"]
  outfields: ["zarr_llc4320_SSH_tiles_4km_filtered"]
  in_mask_list: ["nadir", "None"]
  out_mask_list: ["None"]

model:
  lr: 1e-7
